--系统用户表
DROP TABLE WJ_SYS_USER;
CREATE TABLE WJ_SYS_USER(
    USER_NAME VARCHAR2(16) PRIMARY KEY,
    PASSWORD VARCHAR2(16) NOT NULL,
    FULL_NAME VARCHAR2(50),
    SALT VARCHAR2(100),
    LOCKED CHAR(1) DEFAULT '0',
    ROLE CHAR(1),
    ROLE_CONTEXT VARCHAR2(16),
    CREATE_TIME DATE,
    UPDATE_TIME DATE
);

COMMENT ON COLUMN WJ_SYS_USER.USER_NAME IS '用户名';
COMMENT ON COLUMN WJ_SYS_USER.PASSWORD IS '密码';
COMMENT ON COLUMN WJ_SYS_USER.FULL_NAME IS '用户姓名';
COMMENT ON COLUMN WJ_SYS_USER.SALT IS '盐';
COMMENT ON COLUMN WJ_SYS_USER.LOCKED IS '是否锁定   0：否     1：是';
COMMENT ON COLUMN WJ_SYS_USER.ROLE IS '角色   0：后台管理员权限     1：前台营业部权限    2：前台居间人权限    3：资料维护权限    4：资料审核权限';
COMMENT ON COLUMN WJ_SYS_USER.ROLE_CONTEXT IS '角色内容   0、3、4不填  1需要填写营业部代码  2需要填写居间人代码';
COMMENT ON COLUMN WJ_SYS_USER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN WJ_SYS_USER.UPDATE_TIME IS '更新时间';

--系统菜单表
DROP TABLE WJ_SYS_MENUS;
